### ISSUE TITLE
ping API should return version number instead of "pong"

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#1449] opened 2019-06-17 06:06 UTC
According to the decision made in "Releases, Versions & Patches" document on wiki
https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=21823969
ping API should return version number instead of "pong"
Device Services has made this change

> Version Query
> All services will have a “ping” API that will respond with the version number.  This allows independent services and tooling (listed in the previous section) to query other EdgeX services that it works with and check for compatibility.  For example, when a Device Service built to work with EdgeX 1.0 comes up and it queries Core Data via the ping API and gets a response of 2.0, the device service can choose to log the issue (providing a clear indication of a version mistach) and exit.  The query calling service determines whether it is compatible or not (exiting or continuing). Each services only offers a query API that indicates what version of EdgeX it is.

**Comment by tsconn23** [comment] 2019-07-18 13:40
@cloudxxx8 We will start using the semver tagging at some point and eliminate the version files currently in the edgex-go repo. We would need this solution to return the version based on the Git tag and not the version file, if that's possible.

**Comment by cloudxxx8** [comment] 2019-07-18 14:53
@tsconn23 I thought we still need the version file to be a placeholder.
In device-sdk-go, version.go is a placeholder for source code
https://github.com/edgexfoundry/device-sdk-go/blob/master/version.go#L10
The Makefile will replace the variable during `make build`

When we start using semver, the only timing to access the version number in Git is when executing Jenkinsfile.  Thus, the process would be:

1. Jenkinsfile load the version number from Git and assign to VERSION file at the Jenkins build time
2. Makefile load the version number from VERSION file and assign to the variable in version.go at the `make build` time
3. The go image can access the version number from the variable in version.go when necessary.

Do you think the process is sensible?

**Comment by tsconn23** [comment] 2019-07-22 15:33
Decided Device Service WG call 22-Jul-2019 -- We'll make this change and utilize the existing version information from [here](https://github.com/edgexfoundry/edgex-go/blob/master/version.go). Internally to the core services, we'll need to remove dependence on this constant in favor of the actual Git release tag. But that's a subsequent discussion to be had with the DevOps team.

**Comment by anonymouse64** [comment] 2019-07-22 16:38
Note that the docs explicitly say that the response of the `/ping` endpoint should be `pong`: 

https://github.com/edgexfoundry/edgex-go/blob/b160daecae41719076b92dbd08fb9f72a4325e48/api/raml/core-data.raml#L861-L862

(see https://docs.edgexfoundry.org/core-data.html#ping_get)

It seems that the docs are also incorrect in this case, but note that this change is still an API breaking change, and so if it wasn't considered a bug, this would need to be a major version change. One could argue it's not a bug because the docs site says it should be pong, but I'm guessing that the releases doc @cloudxxx8 links to overrides the docs site in this case, making it a bug and able to be fixed with a patch release

**Comment by tsconn23** [comment] 2019-07-22 18:19
@cloudxxx8 @iain-anderson In relation to @anonymouse64 point above, we'll need to go the feature toggle route.

**Comment by tsconn23** [comment] 2019-07-29 15:11
Closing. Replaced with https://github.com/edgexfoundry/edgex-go/issues/1596

**Closed by tsconn23** 2019-07-29 15:11 UTC
Labels: enhancement, geneva
