### ISSUE TITLE
Unexpected Device-Virtual Abort Causes "Document Is Corrupted" Message (Redis)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#776] opened 2018-11-08 21:47 UTC
See below for "Document is corrupted" error and commensurate Redis logs. This indicates we need to do some work on more gracefully handling an abort from a connected service.

Steps to reproduce:

1.) Make sure Redis is running, execute `flushall`
2.) In terminal window A, bring up EdgeX services via `make run`
3.) In terminal window B, start device-virtual `java -jar device-virtual-0.5.0-SNAPSHOT.jar` and let it run long enough to capture some events
4.) In terminal window B, abort device-virtual via ctrl+C

In window A you should will the following:
```
INFO: 2018/11/08 15:36:28 Deleting the events for device: KMC.BAC-121036CE01
ERROR: 2018/11/08 15:36:28 Document is corrupted
```

If you are running a `redis-cli monitor` session in another terminal window, you will see the following:
```
1541712988.927259 [0 [::1]:55258] "GET" "5be4ac38deafc284e8ed9448"
1541712988.927373 [0 [::1]:55258] "MULTI"
1541712988.927390 [0 [::1]:55258] "UNLINK" "5be4ac38deafc284e8ed9448"
1541712988.927677 [0 [::1]:55258] "ZREM" "reading" "5be4ac38deafc284e8ed9448"
1541712988.927688 [0 [::1]:55258] "ZREM" "reading:created" "5be4ac38deafc284e8ed9448"
1541712988.927696 [0 [::1]:55258] "ZREM" "reading:device:KMC.BAC-121036CE01" "5be4ac38deafc284e8ed9448"
1541712988.927704 [0 [::1]:55258] "ZREM" "reading:name:AnalogValue_40" "5be4ac38deafc284e8ed9448"
1541712988.927715 [0 [::1]:55258] "EXEC"
1541712988.927794 [0 [::1]:55258] "MULTI"
1541712988.927812 [0 [::1]:55258] "UNLINK" "5be4ac38deafc284e8ed9446"
1541712988.927824 [0 [::1]:55258] "ZRANGE" "event:readings:5be4ac38deafc284e8ed9446" "0" "-1"
1541712988.927838 [0 [::1]:55258] "UNLINK" "event:readings:5be4ac38deafc284e8ed9446"
1541712988.927852 [0 [::1]:55258] "ZREM" "event" "5be4ac38deafc284e8ed9446"
1541712988.927863 [0 [::1]:55258] "ZREM" "event:created" "5be4ac38deafc284e8ed9446"
1541712988.927880 [0 [::1]:55258] "EXEC"
1541712988.927965 [0 [::1]:55258] "MULTI"
1541712988.928049 [0 [::1]:55258] "DISCARD"
```

**Comment by andresrinivasan** [comment] 2018-11-08 21:51
Assigned to @andresrinivasan

**Comment by andresrinivasan** [comment] 2018-11-16 02:57
I have confirmed the error you're seeing. There is no additional work to disconnect from Redis. 

Stepping through the code to figure out the source of the error now and will resolve.

**Comment by andresrinivasan** [comment] 2018-11-16 20:00
It's the pseudo referential integrity problem: who is responsible for cleaning up when a composed object is deleted. The call stack looks like

````
deleteEvents (event)
  deleteEvent (event)
    **deleteReadingsById** (event)
    deleteEventById (event)
      deleteEvent (Redis)
        **deleteReadings** (Redis)
````

That last deleteReadings results in an error which propagates up to the error message you see. The quick fix is to not treat this as an error but really what we need to do is fix the contract.

**Comment by andresrinivasan** [comment] 2018-12-06 16:01
There are a number of 1:many object relationships in the Core data model. I would prefer the persistence implementation not be responsible for keeping the integrity of those relationships. Currently it appears the expectation is the the application layer is responsible for this cleanup; this feels like we're asking too much of the application layer. Should we be moving this logic to the model layer where generating a UUID resides?

**Comment by tsconn23** [comment] 2019-03-26 15:48
@andresrinivasan Any further work to be done on this?

**Comment by andresrinivasan** [comment] 2019-04-04 23:36
I believe we experience a collision of terminology. Based on the now decoupled Contract/Model organization. I believe I have heard that the Model layer *is not* responsible for referential integrity; the Contract layer *is* responsible.

**Comment by tsconn23** [comment] 2019-04-05 00:21
You've got a special case there with `deleteAllEvents` unfortunately. Here's a normal [event delete](https://github.com/edgexfoundry/edgex-go/blob/5527999298f60d54d69e91e5a6bf92ea35ff3edd/internal/core/data/event.go#L167) and then here's what [ScrubEvents](https://github.com/edgexfoundry/edgex-go/blob/5527999298f60d54d69e91e5a6bf92ea35ff3edd/internal/pkg/db/mongo/data.go#L184) does. In the latter case it's the DB provider handling both, which I grant you isn't consistent.

**Comment by andresrinivasan** [comment] 2019-04-05 15:35
Got it. I'll open a separate issue for the refactor. This issue can be closed.

**Closed** 2019-04-05 15:42 UTC
Labels: core-services, delhi dot - 0.7.1
