### ISSUE TITLE
Implement support-notifications microservice in Go

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#90] opened 2018-03-28 22:06 UTC
https://github.com/edgexfoundry/support-notifications has to be rewritten in Go.

**Comment by jpwhitemn** [comment] 2018-03-31 20:50
I am working on this task.  Please contact me if you want to assist, but  don't start your own without consulting me.  You can find progress here:  https://github.com/jpwhitemn/edgex-go/tree/notifications

**Comment by jpwhitemn** [comment] 2018-07-20 23:49
Duplicate of #113.  Closing and attributing to California Dot Release.  Work near completion

**Closed by jpwhitemn** 2018-07-20 23:49 UTC
Labels: california, feature, help wanted, support-services
