### ISSUE TITLE
Unable to remove AutoEvents using API

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/edgex-go#2518] opened 2020-04-23 10:56 UTC
# 🐞 Bug Report

### Affected Services

core-metadata

### Is this a regression?
No.

### Description and Minimal Reproduction
AutoEvents can not be removed since added, sending device payload with
```
{
...
"autoEvents":[]
}
```
or
```
{
...
"autoEvents":null
}
```
to /v1/device endpoint using PUT method is not working, perhaps the autoEvents payload is omitted by the omitempty tag?

the only way I found working is to send

{
...
"autoEvents":[{}]
}
to stop the auto events.
it should be removed by something like:
```
{
...
"autoEvents":[]
}
```

## 🌍  Your Environment
**Deployment Environment:**
macOS go1.14
**EdgeX Version:**
master

**Anything else relevant?**

**Comment by AnthonyMBonafide** [comment] 2020-04-29 15:20
After discussing this issue with @brandonforster, this seems to be more of a feature request since this is the intent of the API and is consistent with the other update/PUT HTTP APIs. The reasoning behind this is that updates only happen to fields of data structure that are explicitly mentioned. This is why you have to provide the explicit empty data structure in the array. To change this behavior we would also need to apply this to other update/PUT APIs for consistency which is something I do not think we should tackle in this release. Furthermore, I think this should be closed as it is not a bug since it is intended to operate this way, but opened as a feature request that can be introduced while we are looking to make sweeping changes to the V2 API. I think this is something we should think about as we move forward with the new API.

Thank you @brandonforster , for looking into this.

**Closed** 2020-04-29 15:20 UTC
Labels: 1-low, bug, core-services

**Comment by akramtexas** [comment] 2020-04-29 15:28
@AnthonyMBonafide I saw the recent comment (above) just as I was about to investigate what's been reported in this issue. Making a note that it should be closed out, as it is _not_ a bug 👍
