### ISSUE TITLE
Command service API is stuck at first run 

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2399] opened 2020-02-24 08:36 UTC
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-command

### Is this a regression?

 yes, only happen in master branch

### Description and Minimal Reproduction
When the command service starts, the first time of executing http://localhost:48082/api/v1/device will be stuck.
1. download the nightly-build docker-compose file 
https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
2. use docker-compose up 
`docker-compose -f docker-compose-nexus-redis-no-secty.yml up -d`
3. use curl to send request to http://localhost:48082/api/v1/device 
`curl http://localhost:48082/api/v1/device`
4. the request is stuck

## 🔥 Exception or Error

There is no error log in edgex-core-command container.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Master

**Anything else relevant?**
Cancel the curl request, and send it again, the request works properly. 
Also, this issue could be reproduced by simply restarting command service.
1. `docker-compose -f docker-compose-nexus-redis-no-secty.yml restart command`
2. send curl request again

**Comment by jinlinGuan** [comment] 2020-02-25 02:56
This issue currently causes failure in blackbox-testing.

**Comment by brandonforster** [comment] 2020-02-25 21:34
This might be a regression introduced by #2370 somewhere in the URLClient code. I don't have any insight or theories beyond that.

**Comment by michaelestrin** [comment] 2020-02-26 13:18
This looks to me like a variation of the original [issue](https://github.com/edgexfoundry/edgex-go/issues/2237) that led us down the [refactoring](https://github.com/edgexfoundry/edgex-go/pull/2370) path.  

Possibly newly introduced retry is not working as expected?

Assigned to @brandonforster for investigation/solution.

**Comment by brandonforster** [comment] 2020-02-26 20:35
It looks like logging is throwing an error retrieving its configuration from Consul. I'd say there's two issues here:

1. Why is logging not able to retrieve its configuration?
2. Why is logging not starting making command stop, shutdown, and then restart over and over and over?

**Comment by brandonforster** [comment] 2020-02-28 21:34
I believe I have identified the issue in contracts. Submitting a PR now, I'll use this issue number to update the core-contracts version.

**Comment by michaelestrin** [comment] 2020-03-02 14:40
Closed by https://github.com/edgexfoundry/go-mod-core-contracts/issues/220

**Comment by brandonforster** [comment] 2020-03-02 17:05
Reopening, adding a PR to incorporate those changes into the codebase and fix the BB tests.

**Closed** 2020-03-02 18:11 UTC
Labels: 3-high, bug, core-services, geneva, help wanted
