### ISSUE TITLE
more documentation on configuration properties

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#94] opened 2018-03-29 17:30 UTC
Per Core WG meeting of 3/29, more documentation is needed on the meaning and options of each of the services configuration properties.  Perhaps this is in the code or in a separate file (TBD) - but some guidance to developers is required.

**Comment by tsconn23** [comment] 2019-03-05 15:55
Closing as duplicate of https://github.com/edgexfoundry/edgex-go/issues/802

**Closed by tsconn23** 2019-03-05 15:55 UTC
Labels: delhi, enhancement, good first issue
