### ISSUE TITLE
[scheduler] Interval runOnce feature can not trigger with new action

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#3362] opened 2021-04-14 04:25 UTC
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-scheduler

### Is this a regression?
no

### Description and Minimal Reproduction
1. Run the support-scheduler with DEBUG LogLevel
2. Post interval
```
curl http://localhost:48085/api/v1/interval -X POST -H "Content-Type: application/json" -d '{ "name": "1m", "frequency": "1m", "runOnce": true }'
```
3. The support-scheduler logs:
```
level=INFO ts=2021-04-14T04:03:23.522327Z app=edgex-support-scheduler source=rest_interval.go:123 msg="Posting new Interval: {\"name\":\"1m\",\"frequency\":\"1m\",\"runOnce\":true}"
level=DEBUG ts=2021-04-14T04:03:23.526182Z app=edgex-support-scheduler source=schedule.go:146 msg="adding the interval with id : 10a45083-a61d-4559-ac71-865a2479fb45 at time "
level=DEBUG ts=2021-04-14T04:03:23.526226Z app=edgex-support-scheduler source=schedule.go:158 msg="resetting the interval with id : 10a45083-a61d-4559-ac71-865a2479fb45"
level=INFO ts=2021-04-14T04:03:23.526246Z app=edgex-support-scheduler source=schedule.go:163 msg="added the interval with id : 10a45083-a61d-4559-ac71-865a2479fb45 into the scheduler queue"
level=DEBUG ts=2021-04-14T04:03:23.980842Z app=edgex-support-scheduler source=schedule.go:451 msg="executing interval, detail : {{\"id\":\"10a45083-a61d-4559-ac71-865a2479fb45\",\"name\":\"1m\",\"frequency\":\"1m\",\"runOnce\":true}} , at : 2021-04-14 12:03:23.526242 +0800 CST m=+274.568532174"
level=DEBUG ts=2021-04-14T04:03:23.980987Z app=edgex-support-scheduler source=schedule.go:485 msg="0 interval action need to be executed."
level=DEBUG ts=2021-04-14T04:03:23.981057Z app=edgex-support-scheduler source=schedule.go:523 msg="completed interval, detail : {\"id\":\"10a45083-a61d-4559-ac71-865a2479fb45\",\"name\":\"1m\",\"frequency\":\"1m\",\"runOnce\":true}"
```
## 🔥 Exception or Error
After adding the interval, the interval runs once and completed. 
1. **added the interval** at 04:03:23.526246Z
2. **executing interval** at 04:03:23.980842Z
3. **completed interval** at 04:03:23.981057Z

This interval finished and never run again, even if we add the interval action.
But it will trigger again if we restart the service. 

## 🌍  Your Environment
**EdgeX Version:**
Master branch

**Anything else relevant?**

> runOnce | boolean 
> indicating that this interval runs one time - at the time indicated by the start

https://docs.edgexfoundry.org/1.3/microservices/support/scheduler/Ch-Scheduling/#scheduler-persistence

**Comment by jpwhitemn** [comment] 2021-04-28 16:53
Is this a duplicate of https://github.com/edgexfoundry/edgex-go/issues/2859?

**Comment by weichou1229** [comment] 2021-04-29 01:59
No, it's fail to update the interval's RunOnce field.

**Comment by cloudxxx8** [comment] 2021-06-02 02:17
superseded by #3532

**Closed by cloudxxx8** 2021-06-02 02:17 UTC
Labels: 2-medium, bug, ireland
