### ISSUE TITLE
could not load configuration file

### ISSUE THREAD

**Issue by GulinTong** [edgexfoundry/edgex-go#3071] opened 2021-01-25 03:37 UTC
Hey guys , anyone met this issue ? When I run the main.go, IDEA alert this msg: could not load configuration file (./res/configuration.toml): open ./res/configuration.toml: The system cannot find the path specified.

**Comment by cloudxxx8** [comment] 2021-01-25 04:18
@GulinTong please help provide the clear steps to recreate this issue from other's environment.
However, you might just need to modify the working directory on your IDE

**Comment by jpwhitemn** [comment] 2021-02-05 22:07
@GulinTong  - I am closing this issue due to lack of details.  If you can provide more information or list of steps to reproduce your bug, then we'll reopen the issue and potentially file it as a bug.

**Closed by jpwhitemn** 2021-02-05 22:07 UTC
Labels: question
