### ISSUE TITLE
intervalaction for GET, PATCH, POST not working as DELETE operation in scheduler

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-go#4084] opened 2022-07-07 07:45 UTC
Hi @cloudxxx8 , @cherrycl @lenny-intel ,
Apart from DELETE operation, no other custom defined intervalaction is working if configured for support-scheduler.
To work with GET, POST, PATCH operations, how can we configure the scheduler ?

```
    [IntervalActions.testing1]
    Name = "testing1-events"
    Host = "myhost"
    Port = 59880
    Protocol = "http"
    Method = "GET"
    Target = "core-data"
    Path = "/api/v2/event/all"
    Interval = "quick"
    AdminState = "UNLOCKED"
    Content = "hello"
```
    
    Above configuration shows custom defined intervalaction which doesnt work as expected.
please let me know for any suggestions. Thanks in advance.

**Comment by dipshirajput** [comment] 2022-07-07 09:27
No error msg is there.
but neither am I getting any response to this action in core-data.

@cloudxxx8  Do we have any document which can help me create intervalactions other than DELETE operation? 
Apart from configuration.toml file, where else do I need to add or modify to create any intervalaction apart from delete ?

Thank you.

**Comment by cloudxxx8** [comment] 2022-07-08 03:48
may I know your whole steps to reproduce the issue? did you try to use API to create or update the intervalAction?
I have pasted the the document in another issue and Ginny gave to you in slack.
You be able to check the intervalAction settings by GET API.  If you use the same name, the changes in config won't affect the existing IntervalAction settings.
Please use API instead of config for your testing.

**Comment by cloudxxx8** [comment] 2022-07-11 03:08
since the same question is asked on slack, closing this issue

**Closed by cloudxxx8** 2022-07-11 03:08 UTC
Labels: question
