### ISSUE TITLE
Fail to update job with definition timestamp

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4881] opened 2024-09-04 08:51 UTC
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Create schedule job by API `/api/v3/job` with the following request body
```
POST /api/v3/job
[
  {
    "apiVersion": "v3",
    "scheduleJob": {
      "name": "test_job_8",
      "definition": {
        "type": "INTERVAL",
        "startTimestamp": 1726438942000,
        "endTimestamp": 1736438942000,
        "interval": "10s"
      },
      "actions": [
        {
          "type": "REST",
          "contentType": "application/json",
          "address": "http://localhost:59881/api/v3/ping",
          "method": "GET"
        }
      ]
    }
  }
]
```
2. Update the schedule job
```
[
  {
    "apiVersion": "v3",
    "scheduleJob": {
      "name": "test_job_8",
      "definition": {
        "type": "INTERVAL",
        "endTimestamp": 1746438942000
      }
    }
  }
]
```

## 🔥 Exception or Error
Update job failed.
<pre><code>
[
    {
        "apiVersion": "v3",
        "message": "fail to parse interval string  to a duration time value",
        "statusCode": 400
    }
]

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204 / arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
Send the update request again, will return the job not exist. But the job still can be found by API `/job/name/test_job_8`

**Comment by jackchenjc** [comment] 2024-09-06 14:43
This is an expected behavior at the moment.

We need to consider whether to support updating partial values of the definition object.

cc @cloudxxx8

**Comment by cloudxxx8** [comment] 2024-09-09 03:02
right, we can only partially update the first level fields.
definition has to be full defined.
close this issue because it works as design,

**Comment by cherrycl** [comment] 2024-09-09 03:20
This scenario is not only return error, it seems make the job not found by `PATH /job` API

See the description on **Anything else relevant?** section

**Comment by cloudxxx8** [comment] 2024-09-09 03:43
I see.  That's an issue we should fix.

**Closed** 2024-09-11 01:34 UTC
Labels: bug
