### ISSUE TITLE
[core-data] event endpoint return value grows rapidly and can lead to service failure

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2527] opened 2020-04-28 13:48 UTC
# 🐞 Bug Report
The core-data endpoint /api/v1/event returns an array of Event objects, each of which in turn include an array of Reading objects.

On a running system, this data returned by this endpoint can grown rapidly and doesn't seem to be constrained in any way by core data. For instance, with the latest device-virtual service enabled, which has AutoEvents defined for multiple devices, including one that generates binary data, the resulting response from the event endpoint grows exponentially. At some point, the response gets so large (I'm not sure at what point this happens, but guessing 1-2MB?) that service starts to use chunked encoding to send the full response. When using curl to query this endpoint, I've seen the response object easily crest 100MB.

At some point, the requests start to fail, as the call(s) core-data makes to encode the response start failing. I've also seen the service crash on occasion.

I ran into this bug while testing my latest snap changes. At the moment, due to a device-virtual bug, you may need to bump the service timeouts in order to reproduce this bug using docker:

https://github.com/edgexfoundry/device-virtual-go/issues/104

### Affected Services
The issue is located in: core-data

### Is this a regression?
_Maybe?_

### Description and Minimal Reproduction
Start EdgeX and make sure the latest device-virtual is running with all of its AutoEvents enabled. Start hitting core-data's /api/v1/events endpoint with curl and watch the size of the replies grow.

This is being reported against the latest code in master...

**Comment by AnthonyMBonafide** [comment] 2020-04-28 16:51
Core-data looks like it is simply returning too much data. I think a short term fix for this is to decrease the `Service.MaxResultCount`. The default value is `50,000` which may be too high for the situation.

Long term, I think we can add more functionality for limiting the information returned when getting all events. Right now we are relying on the `Service.MaxResultCount` configuration to limit the number of events returned. However, an event can contain zero or more readings which vary in size, so the number limitation on events might be hard to determine especially for a system which deals with readings and events which vary in size. It might be more useful to have a limit on the Response size, say 500KB. Also, I wonder if for V2 we could explore not returning the Readings for the `GET` Events endpoint and only provide an ID for the client to perform a separate `GET` Reading request to obtain that data.

**Comment by tonyespy** [comment] 2020-04-29 19:20
@AnthonyMBonafide do really consider this low priority? This seems pretty serious to me (i.e. core-data quits responding to the endpoint and can actually crash as a result of this), although I haven't given it enough thought on how we could fix...

**Comment by AnthonyMBonafide** [comment] 2020-04-30 19:32
I was thinking this was lower based on how I was looking at the issue. As I see it, the issue is coming up due to Device Virtual creating big binary events (8MB each) and creating them at a really high rate(every 30s). I was thinking that the issue really resides with the configuration of Device Virtual, rather than being a problem with Core-data. I think that this is a problem, but I see it as being an extreme case. I think adding better limiting functionality for responses is the true fix here. I think we can up the priority. However, I am not sure if this is something we tackle for this release(Geneva).

@tsconn23 , is this a high priority item that we should work on getting in for Geneva?

**Comment by tsconn23** [comment] 2020-05-04 14:42
We talked about this in release planning last week. My takeaway was that this is addressed in V2 with the pagination controls provided by the request types. Even there, the user will need to configure a sensible max page size in the Core to prevent an application from requesting a page size of 10,000 items per page. This behavior/setting has been in the code as long as I have been involved with the project. If Anthony's recommendation to control the response size via configuration works, then I don't think there's an issue here.

**Comment by tonyespy** [comment] 2020-05-04 15:02
@tsconn23 No argument that V2 pagination will solve this. Regarding someone setting a page size to 10k, I think the code needs some reasonable limits for max response size in addition to pagination.

@AnthonyMBonafide I disagree that this is a device-virtual issue. The fact that binary AutoEvents had been configured with a 30s timer just allowed me to hit this issue much quicker than without. If routine maintenance of the db is not happening to clean out pushed events/readings, then this will still happen, it just may take longer with strings or numeric values being pushed. Configure a bunch of devices all pushing uint64s, and you'll see this issue soon enough. The other reason I thought this issue should be considered higher priority is that once the number of pushed events/readings hit a certain threshold, Core Data stops being able to respond to this endpoint, and I've seen it crash as well due to memory starvation.

My recommendation is that we make sure this issue is included in the release notes for Geneva, with emphasis on ensuring that routine database cleaning happens...

**Comment by AnthonyMBonafide** [comment] 2020-05-08 12:08
@tonyespy , good points. As per our discussion yesterday during the Core WG meeting. Core-data is persisting the binary reading values. I verified this using the Redis CLI to obtain one of the events which are associated with a big binary event and observed all the binary data. This is also obvious since issuing a `GET /events` request results in events with readings which have values, most notably the large binary readings. I think there is a bug here which is to avoid persisting the reading values. My apologizes, I didn't know we did not want to store the reading data and did not point this out as the root cause from the beginning. A complete oversight on my part.

**Comment by AnthonyMBonafide** [comment] 2020-05-08 12:09
Is the fix here that we simply just do not persist the reading values or is there some other cleanup or affected area of the system that needs to be addressed as well?

**Comment by AnthonyMBonafide** [comment] 2020-05-08 17:19
This issue depends on the completion of https://github.com/edgexfoundry/go-mod-core-contracts/pull/241.

**Comment by AnthonyMBonafide** [comment] 2020-05-08 17:30
I have verified that this issue only resides with our Redis implementation since the Mongo implementation is converting `go-mod-core-contracts`'s Reading into a Mongo representation: 
https://github.com/edgexfoundry/edgex-go/blob/6d4072662fd20448464d6b9f1b6b045ced6f2767/internal/pkg/db/mongo/models/reading.go#L68-L87

which is not copying over the `BinaryValue` information, so we are good there.

Thank you @jdharms  and @tsconn23  for pointing this out!

**Comment by tonyespy** [comment] 2020-05-14 00:11
@AnthonyMBonafide while your fix greatly reduces the mean time til failure of this endpoint, it doesn't completely fix it. I would think as such, we'd want to keep this open for Hanoi. As @tsconn23 has pointed out, the real fix comes with V2.

I also think we want to recommend that people keep any eye on their database, and ensure that period cleaning of pushed events is always done as a best practice.

**Comment by AnthonyMBonafide** [comment] 2020-05-18 14:20
As per the Core-WG call on May 14th 2020, Reopened issue since the PR which closed this issue does not address the underlying problem. It is expected that this problem will be resolved with V2 as we are looking to add pagination to our APIs to reduce the response sizes.

**Comment by jpwhitemn** [comment] 2020-10-22 15:44
Might be OBE with V2 API.  Jim to check with Cloud

**Comment by cloudxxx8** [comment] 2020-10-26 05:39
This is fixed in V2, because we have default limit for api/v2/event/all

**Comment by cloudxxx8** [comment] 2021-06-03 07:03
close this issue because it has been fixed in V2

**Closed by cloudxxx8** 2021-06-03 07:03 UTC
Labels: 3-high, bug, core-services, ireland
