### ISSUE TITLE
Getting oldest data using Core data API

### ISSUE THREAD

**Issue by MandipJ** [edgexfoundry/edgex-go#1413] opened 2019-06-07 05:27 UTC
**http://localhost:48080/api/v1/event/device/{deviceName}/1** is returning the oldest event posted to this device instead of the latest one.

In [core-data.raml](https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml), its written 
"Newest events are at the top of list.", But when fetch 10 events of a device, it gives me the oldest events of the device and that to oldest are at the top.

Is it a bug or an expected behaviour?

**Comment by jpwhitemn** [comment] 2019-06-12 00:41
Given API documentation sounds like a bug.  This is something we should check against a lot of the service API sets and add blackbox tests for to insure behavior is consistent with docs in the future.  @andyf1967 @frq92290 - heads up on the need for new tests.  @tsconn23 - assign to either @brandonforster or @AnthonyMBonafide as you see fit.

**Comment by tsconn23** [comment] 2019-06-13 23:05
@MandipJ What branch are you using? You do not specify. Further, I am unable to reproduce the condition you report.

@brandonforster @jpwhitemn I don't think there's a bug here. Using the `master` branch I just tried to reproduce the error like so.

- Clean Mongo
- `make build` and `make run` of edgex-go services
- `make build` of [device-random](https://github.com/edgexfoundry/device-random) followed by `cd cmd && ./device-random`
- Device random starts and after it posts 3 events I shut it down. Here are the events it created.

```
> db.event.find()
{ "_id" : ObjectId("5d02d4bddeafc2b79a4d522d"), "created" : NumberLong("1560466621948"), "modified" : NumberLong("1560466621948"), "origin" : NumberLong("1560466621945076000"), "uuid" : "28209e4b-d4dd-4c37-b0a2-c90ed41f8024", "pushed" : NumberLong(0), "device" : "Random-Integer-Generator01", "readings" : [ DBRef("reading", ObjectId("5d02d4bddeafc2b79a4d522c")) ] }
{ "_id" : ObjectId("5d02d4bddeafc2b79a4d5230"), "created" : NumberLong("1560466621950"), "modified" : NumberLong("1560466621950"), "origin" : NumberLong("1560466621944986000"), "uuid" : "a0195fe0-503a-4ae9-aa4b-5848cc45b3a2", "pushed" : NumberLong(0), "device" : "Random-Integer-Generator01", "readings" : [ DBRef("reading", ObjectId("5d02d4bddeafc2b79a4d522e")) ] }
{ "_id" : ObjectId("5d02d4bddeafc2b79a4d5231"), "created" : NumberLong("1560466621951"), "modified" : NumberLong("1560466621951"), "origin" : NumberLong("1560466621944931000"), "uuid" : "afb93a20-b750-408c-a1d0-0016829ea149", "pushed" : NumberLong(0), "device" : "Random-Integer-Generator01", "readings" : [ DBRef("reading", ObjectId("5d02d4bddeafc2b79a4d522f")) ] }
```
The event with UUID `afb93a20-b750-408c-a1d0-0016829ea149` is the most recent given that its Created timestamp is the largest number.

When I execute the following request
`http://localhost:48080/api/v1/event/device/Random-Integer-Generator01/1`

I receive the following event, as expected.
```
[
  {
    "id": "afb93a20-b750-408c-a1d0-0016829ea149",
    "device": "Random-Integer-Generator01",
    "created": 1560466621951,
    "modified": 1560466621951,
    "origin": 1560466621944931000,
    "readings": [
      {
        "id": "31bf32ad-e119-4bbb-8e52-b76d91b0cca4",
        "created": 1560466621948,
        "origin": 1560466621937568000,
        "modified": 1560466621948,
        "device": "Random-Integer-Generator01",
        "name": "RandomValue_Int8",
        "value": "126"
      }
    ]
  }
]
```

**Closed** 2019-06-14 19:46 UTC
Labels: bug, fuji
