### ISSUE TITLE
Redis in the snap triggers apparmor denials

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1442] opened 2019-06-13 22:07 UTC
# 🐞 Bug Report

When using the edinburgh edge nightly snap and enabling Redis there are denials from apparmor (i.e. snap confinement):

```
Jun 13 17:57:13 audit[21915]: AVC apparmor="DENIED" operation="capable" profile="snap.edgexfoundry.redis" pid=21915 comm="redis-server" capability=24  capname="sys_resource"
Jun 13 17:57:13 audit[21915]: AVC apparmor="DENIED" operation="mknod" profile="snap.edgexfoundry.redis" name="/run/redis_6379.pid" pid=21915 comm="redis-server" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
```

### Affected Services

Redis in the snap triggers denials, but AFAICT this doesn't stop Redis from accessing anything it needs so we can probably ignore these, but it would be ideal to not have them as it may confuse users.

The fix for the second denial is probably just to set the pid file in the redis.conf file, however the `sys_resource` capability is only available through the `greengrass-support`, `docker-support`, kubernetes-support`, `pulseaudio`, `process-control`, and `system-trace` interfaces, of which only `process-control` or `system-trace` seem remotely plausible to grant to EdgeX. But if Redis runs fine anyways, perhaps it's okay to just ignore that.

### Description and Minimal Reproduction

```
snap install edgexfoundry --channel=edinburgh/edge
sleep 30
snap set edgexfoundry dbtype=redis
```

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu Desktop 18.04.2 on x86

**EdgeX Version:**

`1.0.0-20190612+fd102ad9` (from `snap info edgexfoundry | grep installed`)

**Comment by tonyespy** [comment] 2019-06-13 22:17
Are there really no labels for priority? If there were, I was going to categorize this as low.

For the second denial, using 'process-control' seems like the right interface to use.

**Comment by anonymouse64** [comment] 2019-06-13 22:44
@tonyespy do we really want to provide `process-control` to the snap though? It is a privileged interface so we would need to justify it on the forum and right now all I have for justification is "it makes the message go away".

@andresrinivasan do you know why Redis needs sys_resource capability and if there's any way to configure Redis to not try and use that? Does it affect performance at all?

**Comment by anonymouse64** [comment] 2019-06-20 18:54
Since this is a low priority bug, I think it's okay to let wait until Fuji, unless we get feedback from edinburgh users that it's problematic in which case we can evaluate a edinburgh dot release

**Comment by anonymouse64** [comment] 2019-11-01 18:35
Well, didn't get to this for Fuji either, so moving to Geneva

**Comment by tonyespy** [comment] 2020-05-07 18:03
This didn't make it for Geneva, so removing milestone.

**Comment by bnevis-i** [comment] 2021-06-18 17:38
@tonyespy Tony, should this be in scope for Jakarta?

**Comment by tonyespy** [comment] 2021-06-23 23:13
As of Hanoi release, the AppArmor denial for the pid file no longer happens (verified for Ireland too). The denial for the use of cap:sys_resource still happens though:

`Jun 13 17:57:13 audit[21915]: AVC apparmor="DENIED" operation="capable" profile="snap.edgexfoundry.redis" pid=21915 comm="redis-server" capability=24  capname="sys_resource"
`
The cause of this is that when redis starts, it checks its `server.maxclients` setting against the system's current resource limit for open files, and if the current resource limit is too small, it tries to adjust the number of open files using the standard C library `setrlimit` call, which under the covers uses the system calls `getcap/setcap`. It's these calls the trigger the AppArmor denial. Note, the code is written in such a way that if it cannot adjust the system resources, it adjusts its internal constants to deal with the given resources. As such, this denial can be just be considered "noise". As such, I'm closing this issue.

It also might not be a bad idea for us to adjust the max number of clients to a more reasonable number, as 10000 seems a bit excessive for a typical EdgeX instance.

**Closed by tonyespy** 2021-06-23 23:13 UTC
Labels: 1-low, bug, snap
