### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by jiechenjiester** [edgexfoundry/edgex-go#3872] opened 2022-01-26 07:59 UTC
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
Notification

### Is this a regression?
no

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
<img width="1481" alt="截屏2022-01-26 下午3 18 09" src="https://user-images.githubusercontent.com/59988289/151119841-6e10c3fe-1065-44a0-a191-910ab4cb9cab.png">
<img width="1481" alt="截屏2022-01-26 下午3 24 38" src="https://user-images.githubusercontent.com/59988289/151122569-5b77ba46-82ee-4888-8b12-16dd07ba0fb8.png">
<img width="1481" alt="截屏2022-01-26 下午3 31 01" src="https://user-images.githubusercontent.com/59988289/151122831-1f51bb2a-1bde-416a-a593-175a327249a6.png">

I create a Subscription data.
There is no notification whether the device is created or the service is stopped.
And I can't serach any result. 
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:make run app-sample**

**EdgeX Version [**REQUIRED**]:2.1**

**Anything else relevant?**

**Comment by cloudxxx8** [comment] 2022-01-31 07:16
Please fill out which version you are using.
In https://docs.edgexfoundry.org/2.1/microservices/core/metadata/Ch-Metadata/#configuration-properties , there is a configuration called `PostDeviceChanges`, and the default value is `false`.  You have to enable it before using this feature.
You can enable it by adding an environment variable in the core-metadata in the docker-compose file:
`Notifications_PostDeviceChanges: "true"`

Also, the `Subscription` you created is wrong.  The `label` has to match the value of `Notifications_Label` in the core-metadata configuration, and its default value is `metadata`, not `notify`.

**Comment by jpwhitemn** [comment] 2022-02-14 23:49
@jiechenjiester - per the info supplied by cloudx888 can you verify this issue has been resolved, or if not can you provide additional details.  We'll close this issue as not a bug in a week if we do not hear any addition feedback from you.

**Comment by JamesKButcher** [comment] 2022-03-11 08:15
No feedback so closing at this time

**Closed by JamesKButcher** 2022-03-11 08:15 UTC
Labels: question

**Comment by bighb69738** [comment] 2022-04-22 06:20
Hi all :
I tried to set the true for metadaia of PostDeviceChanges.
But it can not send the notification, when I delete a device or add a device with virtual device service.

<img width="1438" alt="截圖 2022-04-22 下午2 19 15" src="https://user-images.githubusercontent.com/38970513/164615166-2d011002-6c4c-4380-9703-58151983a265.png">

<img width="1148" alt="截圖 2022-04-22 下午2 20 34" src="https://user-images.githubusercontent.com/38970513/164615276-dbe38f8b-ab92-4c48-89f9-399eea0decef.png">
