### ISSUE TITLE
Cannot found transmission data which resendcount > 1 when querying transmission by status

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1316] opened 2019-05-07 09:57 UTC
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. Startup EdgeX
2. Create transmissions using [import transmission](https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/support-notifications-importer.postman_collection.json) script of blackbox testing.
3. Get /api/v1/transmission/{{failedStatus}}/{{limit}.

> Method: Get
> URL: http://localhost:48060/api/v1/transmission/failed/2

Actual results: Only one record is found, but there are 2 records with failed status on the import script.
Expected results: 2 records whose status is failed are found.

**Comment by tsconn23** [comment] 2019-05-10 21:17
Unable to reproduce using build from `master` running natively. Not sure where the Docker container referenced above is sourced from. Following the steps above, I obtain the following result. 2 records returned.
```
[
    {
        "created": 1557522274195,
        "modified": 1557522274195,
        "id": "7af24a4f-7de1-4cd1-a3fc-5644382e526a",
        "notification": {
            "id": "a4843fc8-0d5a-4b6b-9c94-119b284b4f60",
            "slug": "notice-021"
        },
        "receiver": "Jack",
        "channel": {
            "type": "REST",
            "url": "http://localhost:5566/test"
        },
        "status": "FAILED",
        "resendcount": 1,
        "records": [
            {
                "status": "FAILED",
                "response": "true",
                "sent": 1472439914709
            }
        ]
    },
    {
        "created": 1557522915489,
        "modified": 1557522915489,
        "id": "77a44c42-88fa-4b35-8f85-3aa513edf1f5",
        "notification": {
            "id": "6b19d541-a40e-4691-8b66-256fca263941",
            "slug": "notice-021"
        },
        "receiver": "Jack",
        "channel": {
            "type": "REST",
            "url": "http://localhost:5566/test"
        },
        "status": "FAILED",
        "resendcount": 1,
        "records": [
            {
                "status": "FAILED",
                "response": "true",
                "sent": 1472439914709
            }
        ]
    }
]
```

**Comment by cherrycl** [comment] 2019-05-13 08:18
@tsconn23 This issue only occurred when resendcount is greater than 1 (ex. 2, 3).  The resendcount value on the above returned records is "1".

**Comment by tsconn23** [comment] 2019-05-13 16:27
The reason this is happening is because the query is written to return `resendCount` values less than what is specified via the URL. Here's the query:
`return mc.getTransmissionsLimit(bson.M{"resendcount": bson.M{"$lt": resendLimit}, "status": status})`

If the expectation is that this should be a `less than or equal to` query, that can be easily changed. Also, it does not appear that Redis is returning the correct results.

**Comment by cloudxxx8** [comment] 2019-05-14 13:56
@tsconn23 and @akramtexas  the original design of this API doesn't mean `{limit}` is `resentLimit`, because `resentLimit` is a global configuration property and it should not be treat as a query criterion of a specific `Transmission`.
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/support-notifications/res/configuration.toml#L2

Unfortunately, we don't have a clear definition of this parameter in RAML.
https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/support-notifications.raml#L1163

However, the limit parameter of `Transmission` is really important because one `Notification` might produce lots of Transmission according to how many subscription and resend associated to the `Notification`.  That's why all the GET API of `Transmission` contains `{limit}`

**Comment by tsconn23** [comment] 2019-05-14 14:27
I went back through history on this and it appears the handling of `limit` was broken during the Go to Java conversion. Here's an example from the Java support-notifications service where the `limit` URL parameter is used to cap the number of results
https://github.com/edgexfoundry/support-notifications/blob/ddebc1ba67919b7f25b82cc7239b7a0128484b1a/src/main/java/org/edgexfoundry/support/notifications/controller/impl/TransmissionControllerImpl.java#L146

And here's the same from the original `edgexfoundry-holding` repo where the `limit` route segment is equated to `resendLimit`
https://github.com/edgexfoundry/edgex-go/blob/edad515d3a4fb664691173592ef9ca6089c128d9/internal/support/notifications/rest_transmission.go#L228

@cloudxxx8 Please confirm that you want the handling of `limit` to be modified on all `transmission` routes in the support-notifications service to apply to the maximum number of results returned. If so, I will close all related issues and open a new one to fix all the routes.

**Comment by cloudxxx8** [comment] 2019-05-14 14:29
thanks, @tsconn23 , yes, that is what we want.

**Comment by tsconn23** [comment] 2019-05-14 14:50
Closing -- replaced with https://github.com/edgexfoundry/edgex-go/issues/1338

**Closed by tsconn23** 2019-05-14 14:50 UTC
Labels: invalid
