### ISSUE TITLE
Services should support stopping gracefully with SIGTERM

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1306] opened 2019-05-03 01:41 UTC
SIGTERM is a standard Unix signal that is sent to daemons to tell them to stop gracefully, i.e. when the system is shutting down, or an upgrade is about to be performed, etc. Currently these signals are entirely ignored by all EdgeX services, it would be nice if they could be handled the same way as `os.Interrupt` is currently. 

Note that windows has no such concept so it would be Linux and macOS specific behavior.

**Comment by anonymouse64** [comment] 2019-05-03 02:17
Interestingly enough the services only ignore the SIGTERM when in the snap, if I just run the services natively not as part of a systemd service then they handle SIGTERM properly.

**Comment by brandonforster** [comment] 2019-05-03 09:36
This might be a regression introduced with my work on #995.

**Comment by michaelestrin** [comment] 2019-09-30 15:26
@anonymouse64 is this still an issue (and needs to be worked) or has it been resolved by changes merged to master since this issue was created?

**Comment by anonymouse64** [comment] 2019-09-30 15:54
I need to re-evaluate this, unclear if it now works or not

**Comment by michaelestrin** [comment] 2019-09-30 16:04
Ask is to test using one of the core services that has been updated to use the new common bootstrap package (i.e. core-data, core-metadata, system-management-agent, etc.).

**Comment by michaelestrin** [comment] 2019-12-06 15:49
> I need to re-evaluate this, unclear if it now works or not

@anonymouse64 when will you have an opportunity to test this and determine if this issue is still valid?

**Comment by anonymouse64** [comment] 2019-12-06 16:51
Probably not anytime soon. You can close this if you can't reproduce

**Comment by michaelestrin** [comment] 2019-12-06 18:17
Closing without testing.  If this is still a problem that causes someone heartache, I expect they will reopen this issue.

**Closed by michaelestrin** 2019-12-06 18:17 UTC
Labels: core-services, export-services, geneva, support-services, system-management
