### ISSUE TITLE
Create a critical notification takes time over 1s

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1187] opened 2019-03-21 02:56 UTC
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. Post /api/v1/notification with the following body.
```
Method: POST
URL: http://localhost:48060/api/v1/notification
Body:
{
    "slug": "notice-002",
    "sender": "System Management",
    "category": "HW_HEALTH",
    "severity": "CRITICAL",
    "content": " [ WARNING ] Room's temperature is 103 °F , it's over upper limit 100 °F.",
    "labels": [
        "room",
        "temperature"
    ]
}
```

Actual results: Post successful with 200 return code and response time is always more than 1000ms.
Expected results: Post successful and response time is less than 800ms.

[**Master**] Blackbox test result:

> 20:43:16 ↳ Create a critical notification
> 20:43:16   POST http://edgex-support-notifications:48060/api/v1/notification [202 Accepted, 133B, **1124ms**]
> 20:43:17   ✓  Status code is 202
> 20:43:17   1. Response time is less than 200ms
> 20:43:17   ✓  Content-Type is present
> 20:43:17   ✓  Content-Type is text/plain
> 20:43:17   ✓  Critical notification had been proceessed and transmissions are created.  
> 20:43:17   ✓  Response body is correct

[**Delhi**] Blackbox test result:

> 21:06:14 ↳ Create a critical notification
> 21:06:14   POST http://edgex-support-notifications:48060/api/v1/notification [202 Accepted, 133B, **17ms**]
> 21:06:14   ✓  Status code is 202
> 21:06:14   ✓  Response time is less than 200ms
> 21:06:14   ✓  Content-Type is present
> 21:06:14   ✓  Content-Type is text/plain
> 21:06:14   ✓  Critical notification had been proceessed and transmissions are created.  
> 21:06:14   ✓  Response body is correct

**Comment by cloudxxx8** [comment] 2019-03-21 03:32
it's a regression and performance issue because this API is much slower than others

**Comment by cloudxxx8** [comment] 2019-03-21 03:37
In master it is 1124 ms, but it is only 17 ms in delhi

**Comment by tsconn23** [comment] 2019-03-21 22:30
Are the actual and expected results reversed in the issue report?

**Comment by cloudxxx8** [comment] 2019-03-22 10:21
currently, we extend the response time threshold to 800 ms (expected) , but the actual result in master is over 1000 ms.

**Comment by tsconn23** [comment] 2019-03-22 14:21
> currently, we extend the response time threshold to 800 ms (expected) , but the actual result in master is over 1000 ms.

Right, got it. So the actual and expected are reversed in the initial issue report because there it says.

>Actual results: Post successful and response time is less than 800ms.

I get what you mean though

**Comment by cloudxxx8** [comment] 2019-03-22 14:29
@tsconn23 I just understood what you mean...
yes, the issue description is wrong
@cherrycl please revise it

**Comment by cherrycl** [comment] 2019-03-23 01:50
@tsconn23 @cloudxxx8  I fixed the mistake, sorry for that.

**Comment by akramtexas** [comment] 2019-03-26 15:07
My apologies for not noticing (earlier) that this issue has been assigned to me. I'll look into it shortly 👍

**Comment by akramtexas** [comment] 2019-03-29 18:56
- In discussing with @andyf1967 my understanding is that this issue is _independent_ of the following issue: [Support-Notification: No response data returned when endDate set to "1600000" on /end/{{endDate}}/{{limit}} api #186](https://github.com/edgexfoundry/edgex-go/issues/186)

**Comment by akramtexas** [comment] 2019-04-01 21:15
- After making some updates to my docker-compose.yml, I'm able to deploy the `master` branch locally as services hosted in `docker` containers, following which I can recreate the issue.
- Investigating the root cause now.

**Comment by akramtexas** [comment] 2019-04-02 19:10
- Investigating whether this function is causing the time delay:
`
func (mc MongoClient) GetSubscriptionByCategoriesLabels(categories []string, labels []string) ([]contract.Subscription, error) {
	return mc.getSubscriptions(bson.M{"subscribedCategories": bson.M{"$in": categories}, "subscribedLabels": bson.M{"$in": labels}})
}
`

**Comment by akramtexas** [comment] 2019-04-02 20:31
- Did not find anything unusual about the way the function is used...
```
subs, err := dbClient.GetSubscriptionByCategoriesLabels(categories, n.Labels)
``
- Created a bunch of notifications in `DB` to see if the fetch operation slows down with increasing documents in `MongoDB`
- Unable to create issue in local environment.
- Resuming investigation when services are hosted in docker containers, following which I can _still_ recreate the issue.

**Comment by akramtexas** [comment] 2019-04-02 21:41
- I am able to get at the logging done in `docker containers`. 
- With that, I see that, when the command to create a critical notification is initiated, the system tries to send email message repeatedly. 
- These email-send attempts consume time and eventually are given up as failing (evidently caused by "x509: certificate signed by unknown authority")
- Here is relevant logging from the containerized `notifications` service:

```
level=INFO ts=2019-04-02T20:56:45.9235712Z app=edgex-support-notifications source=rest_notification.go:45 msg="Posting Notification: {\"id\":null,\"slug\":\"notice-028\",\"sender\":\"System Management\",\"category\":\"HW_HEALTH\",\"severity\":\"CRITICAL\",\"content\":\" [ WARNING ] Room's temperature is 103 °F , it's over upper limit 100 °F.\",\"labels\":[\"room\",\"temperature\"]}",
level=INFO ts=2019-04-02T20:56:45.9300808Z app=edgex-support-notifications source=rest_notification.go:55 msg="Critical severity scheduler is triggered for: notice-028",
level=ERROR ts=2019-04-02T20:56:46.240055Z app=edgex-support-notifications source=sending_service.go:90 msg="Problems sending message to: andy@abc.def,tom@abc.def, issue: x509: certificate signed by unknown authority",
level=INFO ts=2019-04-02T20:56:47.023853Z app=edgex-support-notifications source=middleware.go:43 correlation-id=541851ce-4303-4e7b-ad11-4bc3d0851654 path=/api/v1/ping msg="Begin request",
level=INFO ts=2019-04-02T20:56:47.0290541Z app=edgex-support-notifications source=middleware.go:34 correlation-id=541851ce-4303-4e7b-ad11-4bc3d0851654 duration=5.1831ms msg="Response complete",
level=ERROR ts=2019-04-02T20:56:47.4536566Z app=edgex-support-notifications source=sending_service.go:90 msg="Problems sending message to: john@abc.def,sam@abc.def, issue: x509: certificate signed by unknown authority",
level=ERROR ts=2019-04-02T20:56:48.5875452Z app=edgex-support-notifications source=sending_service.go:90 msg="Problems sending message to: karl@abc.def,jeff@abc.def, issue: x509: certificate signed by unknown authority",
level=ERROR ts=2019-04-02T20:56:49.9042325Z app=edgex-support-notifications source=sending_service.go:90 msg="Problems sending message to: davis@abc.def,david@abc.def, issue: x509: certificate signed by unknown authority",
level=ERROR ts=2019-04-02T20:56:51.0767282Z app=edgex-support-notifications source=sending_service.go:90 msg="Problems sending message to: elliot@abc.def,elvin@abc.def, issue: x509: certificate signed by unknown authority",
```

**Comment by akramtexas** [comment] 2019-04-02 21:49
@cherrycl and @weichou1229 - Could you please share insight into the nature of this particular test (in terms of expected use-case as it relates to sending of email and expected outcome)? Thanks.
- I examined `github.com/edgexfoundry/blackbox-testing/bin/postman-test/collections/support-notifications-importer.postman_collection.json` etc., but can't infer whether the side-effect (that I'm observing) are intentional per the black box test... 
- I also examined (grepped, really) the tests for mention of instances of the following, but found no relevant `support-notifications` insight:
```
Response time is less than 200ms | AssertionError: expected 106928 to be below 200
```

**Comment by cloudxxx8** [comment] 2019-04-03 10:49
@akramtexas 
you might not need to run black box test to reproduce this issue.  the root cause of this issue is the service process critical notification synchronously, so the performance would be always unacceptable.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/notifications/rest_notification.go#L56
https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/notifications/normal_distribution.go#L23
Please see the sequence diagram of the original design document:
https://docs.edgexfoundry.org/Ch-AlertsNotifications.html
The distribution should always be asynchronously
Thus, the code in normal_distribution.go might become.
`go distribute(n)`
It would be marked PROCESSED no matter the distribution is successful or not.

**Comment by akramtexas** [comment] 2019-04-03 16:29
- @cloudxxx8 Thanks for the detailed note! So I _am_ able to recreate this issue (_outside_ of black-box testing). 
- As I may have noted (in a recent comment above), what happens is that when the command to create a critical notification is initiated, the system tries to send email message repeatedly. These email-send attempts consume time and eventually are given up as failing (evidently caused by `x509: certificate signed by unknown authority`).
- The Go code for the service, I believe, works as expected. But yes, to your point on improving performance (possibly by making the service process the critical notifications asynchronously), please create a separate issue. If you wish, I'll be glad to chat with you to make sure we're aligned 👍

**Comment by cloudxxx8** [comment] 2019-04-07 10:20
@akramtexas `x509: certificate signed by unknown authority` is a different issue.  We should create another issue to discuss.
Making notifications asynchronously is the original design and meet the topic of this issue.  Why do we need a separate issue?  If the Subscriptions exist, the current response time is unacceptable.  If you agree, I can open a PR to fix it.  Please help advise.  Thanks.

**Comment by akramtexas** [comment] 2019-04-10 20:39
@cloudxxx8 Yes, the `x509: certificate signed by unknown authority` is a set-up issue. Sure, let's connect and discuss a resolution: We can also discuss your earlier point (having to do with, `It would be marked PROCESSED no matter the distribution is successful or not.`). Thanks.

**Comment by akramtexas** [comment] 2019-04-15 15:57
@weichou1229 @cloudxxx8 @jpwhitemn - The discussion at the recent `QA/Test WG` meeting was most helpful 💯  
- I now appreciate better the QA test case and how it relates to the (current) implementation in golang (initially was Java, before being migrated to golang). I had given the design some thoughts when investigating this issue, but wasn’t sure if making the (email-generation) call asynchronous was the right thing to do (use-case-wise). But it makese sense, in light of the WG meeting discussion (i.e. making the email-generation asynch). 
- I will address this and create a PR once done. Thank you, gentlemen 👍

**Comment by cloudxxx8** [comment] 2019-04-16 15:02
@akramtexas thanks for the help on this issue.  I am reviewing the PR.

**Closed** 2019-04-17 19:43 UTC
