### ISSUE TITLE
When accessing the AppService menu, an error occurs: "Oops!!! registry center service is unavailable!

### ISSUE THREAD

**Issue by amahure-hitachi** [edgexfoundry/edgex-go#4753] opened 2024-01-25 06:57 UTC
![image](https://github.com/edgexfoundry/edgex-go/assets/120502647/e14bf7b0-9b84-42b3-98bc-1a1a5ef77a1e)

I used edgex-compose 3.1.0, When accessing /api/v3/registrycenter/ping, it returns a code 500，‘unable to get consul acl token'.

For More reference please follow https://github.com/edgexfoundry/edgex-ui-go/issues/672#issuecomment-1907390595 
https://github.com/edgexfoundry/edgex-ui-go/issues/672

**Comment by lenny-intel** [comment] 2024-01-25 22:40
This is a duplicate of https://github.com/edgexfoundry/edgex-ui-go/issues/672 which is already in the backlog

**Closed by lenny-intel** 2024-01-25 22:40 UTC
Labels: bug
