### ISSUE TITLE
Readings pushed to Core Data trigger Invalid Object ID error messages from Core Metadata

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#128] opened 2018-04-10 14:12 UTC
While testing my edgex core snap (version: 0.5.1+cali-20180322) on an Ubuntu 16.04 LTS Desktop system (amd64), I noticed the following error messages every time a new event is pushed from device-virtual to core-data output on the terminal used to start edgex:

_INFO: 2018/04/10 09:39:18 Posting Event: {"id":"","pushed":0,"device":"KMC.BAC-121036\
CE01","created":0,"modified":0,"origin":1523367558014,"schedule":null,"event":null,"r\
eadings":[{"id":"","pushed":0,"created":0,"origin":1523367558014,"modified":0,"device\
":"KMC.BAC-121036CE01","name":"AnalogValue_20","value":"41.76"}]}

ERROR: 2018/04/10 09:39:18 mgoGetDeviceById Invalid Object ID KMC.BAC-121036CE01_

The Error message is being generated by the function mgoGetDeviceById() (src/core/metadata/mongoOps.go), in response to a call from Core Data's eventHandler function (src/core/data/event.go):

```
     // Get device from metadata
     deviceFound := true
     // Try by ID
     d, err := mdc.Device(e.Device)
     if err != nil {
       // Try by name
       d, err = mdc.DeviceForName(e.Device)
       if err != nil {
         deviceFound = false
       }
     }
     // Make sure the identifier is the device name
     if deviceFound {
       e.Device = d.Name
     }

     // See if metadata checking is enabled
     if configuration.MetaDataCheck && !deviceFound {
       loggingClient.Error("Device not found for event: "+err.Error(), "")
       http.Error(w, err.Error(), http.StatusNotFound)
       return
     }

```
There are a few problems with this code:

 * it does a lookup by deviceId, however the event from device-virtual doesn't include a deviceId, it just includes a devicName, hence this call **will always fail**
 * the code checks after the lookups to see whether a MetadataCheck was required, thus the code makes two REST API calls, neither of which may have been required
 * the REST call returns the entire device, however it's then just discarded.  Ideally, Core Metadata should expose DeviceExists endpoints that just return bool results.  In lieu of this change, the metadata client could define similar functions. Passing `models.Device` structs around by value, especially when they're not being used is just wasted compute cycles.
 * `models.Event `and `models.Readings` have a field names "Device", which is confusing as I would think this would refer to a `models.Device`.  In reality these fields are deviceName, and probably should be updated (there's even a comment in each struct definition clarifying this)

**Comment by tonyespy** [comment] 2018-04-10 14:30
Also, the log message in Core Metadata should probably be DEBUG (if/when we get log level filtering).  It makes no sense for a lookup endpoint log normal query failures, these should be done by the client.

**Comment by tsconn23** [comment] 2018-04-11 22:04
@tonyespy @jpwhitemn This is a duplicate of https://github.com/edgexfoundry/edgex-go/issues/71 but with a lot more descriptive information. I really don't like how the Device property is dual purposed. It's quite widespread.

**Comment by tonyespy** [comment] 2018-04-14 14:40
@tsconn23 Re: the Device property is dual-purposed, yes I agree. It would make sense to have these objects include explicit DeviceName or DeviceId (or both) fields.

**Comment by tsconn23** [comment] 2018-05-10 16:19
@tonyespy When you have time, let me know if the above PR merge has addressed this issue. We do still have a dual-purposed property, however primacy is given to its usage as "name" rather than "id" which, in my testing, has greatly reduced the occurrence of these errors. 

Subsequent refactoring will address the model itself, but that then spills over into RAML, docs, etc.

**Closed** 2018-05-21 22:43 UTC
Labels: core-services, question, request for comments
