### ISSUE TITLE
The description field is empty when posting device profile using /api/v1/deviceprofile

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1320] opened 2019-05-08 09:42 UTC
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. Startup EdgeX
2. Post /api/v1/deviceprofile with the following body.

> Method: POST
> URL: http://localhost:48081/api/v1/deviceprofile
> {
>   "origin":1471806386919,
>   "name":"TestProfileToPostUniqe",
>   "description":"BACnet Honeywell thermostats",
>   "manufacturer":"Honeywell",
>   "model":"ABC123",
>   "labels":["bacnet","thermostat","Honeywell"],
>   "coreCommands":[
>     {
>       "origin":1471806386919,
>       "name":"cooling point1",
>       "get":
>         {
>           "path":"/cooling",
>           "response":{
>             "code":"200",
>             "errorDescription":"not a float",
>             "expectedValues":"temperature"
>           }
>         },
>       "put":{
>         "path":"/cooling",
>         "response":{
>           "code":"200",
>           "errorDescription":"not a float",
>           "expectedValues":"temperature"
>         },
>         "parameters":[  
>                {  
>                   "name":"coolingpoint",
>                   "value":"float",
>                   "uom":"string"
>                }
>         ]
>       }
>     }
>   ],
>   "deviceCommands":[{
>     "get":[
>       {
>         "parameter":"CurrentHumidity",
>         "property":"presentValue",
>         "operation":"get",
>         "object":"AnalogValue_22"
>       }
>     ]
>   }]
> }

Actual results: Request sent successful, but the description field is empty on Database.
Expected results: Value of the description field is the same as posting body.

**Comment by tsconn23** [comment] 2019-05-08 18:47
The root cause is in go-mod-core-contracts. Closing this issue, replacing with https://github.com/edgexfoundry/go-mod-core-contracts/issues/93

**Closed by tsconn23** 2019-05-08 18:47 UTC
Labels: bug
