### ISSUE TITLE
Improve and simplify the Device Profile (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#830] opened 2018-11-19 23:41 UTC
Improve/simplify the Device Profile – removing unused elements and better naming of elements given recent SDK work.  Should help with issue #93

**Comment by iain-anderson** [comment] 2018-11-28 14:55
In addition to changes in the content of a device profile, I think we should deprecate the facility for uploading a profile from a YAML file and instead allow uploading from JSON. This removes the requirement for another parser and the need for developers to know another format.

**Comment by jduranf** [comment] 2018-11-28 15:32
@iain-anderson sorry to disagree, but YAML is more human friendly, so it's more easy to create a profile using YAML. Besides that, currently you can upload a profile using a JSON.

**Comment by SteveOss** [comment] 2018-11-28 15:36
The feedback from the IOTech developers building services is that using YAML for writing profiles
and the lack of decent error reporting when something goes wrong (like a missing space ! ), is a
major headache. Should look at a YAML profile and a JSON equivalent, so we can evaluate the pros and
cons.

**Comment by iain-anderson** [comment] 2018-11-28 15:59
Here is one of the modbus example profiles in both formats. The main difference is that in json the grouping of structs and arrays is with brackets and in yaml it is using whitespace.

[padre.json.txt](https://github.com/edgexfoundry/edgex-go/files/2625619/padre.json.txt)
[padre.yaml.txt](https://github.com/edgexfoundry/edgex-go/files/2625620/padre.yaml.txt)

**Comment by tsconn23** [comment] 2018-11-28 21:08
Formatting aside, what specific elements in the DeviceProfile does this issue refer to? What aspects of the profile need to be simplified / removed / massaged / etc? Let's get that documented (or scheduled for discussion on a Dev Svcs call) and then look at formatting changes (which might properly be a separate issue). @cloudxxx8 @tonyespy for visibility.

**Comment by cloudxxx8** [comment] 2018-11-30 13:33
Yeah, formatting should be another topic.  Let's focus on data model here.  I am not good at naming, so I just bring up my concerns in profile data model:

1. resources and deviceResources are different fields, but easy to confuse people.
2. We have get/set operation and get/put command, so we had better make them consistent.
3. In command model, the path field should be moved to the upper level, because the path of get and put in the same command should be the same.  Currently, it is redundant field in get/put.
4. In get/set resource operation, "property" field is always "value".  I am not sure the meaning of this field.
5. In deviceResources, "units" model should be re-designed, because some fields in it is useless, such as readWrite and type.  "units" cannot be written and is always "String".

May we have another issue for improving "Device" model?

**Comment by iain-anderson** [comment] 2018-11-30 14:00
1. deviceResources are typed as DeviceObject in the code, perhaps use that name?
2. I think get/put is used to reflect http terminology for the commands. Suggest we remove commands section altogether, they should be inferred from resources.
3. See above.
4. This would be useful if we could define multiple properties per deviceResource/DeviceObject. However there would then be confusion as to which property "units" refers to. Suggest we add a units field to the property structure and allow any number of properties with arbitrary names.
5. See above.

**Comment by iain-anderson** [comment] 2018-11-30 14:04
Also,
6. Remove "size", "word", "lsb" and "signed" as these are no longer used?
7. Are we intending to support mixed get and set operations within a resource? If not the "operation" field could be removed.

**Comment by cloudxxx8** [comment] 2019-01-21 06:06
We need an extendable field in Device, Addressable, and Device Profile.  It could be a simple string map.

**Comment by tonyespy** [comment] 2019-01-28 16:18
@cloudxxx8 I'm not sure I understand your previous comment about the need for an extendable field in the `Device`, `Addressable`, and `DeviceProfile` structs? Can you please explain why for each, and include detailed use cases? As I mentioned in issue #1007, if you think we need *new* fields in structs, then please create new issues for each struct. This issue was about simplifying device profiles.

**Comment by tonyespy** [comment] 2019-01-28 16:23
> In addition to changes in the content of a device profile, I think we should deprecate the facility for uploading a profile from a YAML file and instead allow uploading from JSON. This removes the requirement for another parser and the need for developers to know another format.

If people are really having that much difficulty with YAML, my vote would be to keep the YAML format for backwards compatibility, and add support for JSON. Having worked with both formats, I find that YAML is a more editor friendly format.

**Comment by tonyespy** [comment] 2019-01-28 16:57
>     3. In command model, the path field should be moved to the upper level, because the path of get and put in the same command should be the same.  Currently, it is redundant field in get/put.

I'm not sure I understand your point here? Please see my previous comment about the difference between commands and resources. Can you provide an example from an existing device profile?

>     4. In get/set resource operation, "property" field is always "value".  I am not sure the meaning of this field.

@trcox mentioned that the original idea was to provide more flexible type operations, however as this was never actually implemented, we could probably just go ahead and get rid of this field.

>     5. In deviceResources, "units" model should be re-designed, because some fields in it is useless, such as readWrite and type.  "units" cannot be written and is always "String".

As I understand it, **units** was designed for clients to help them display readings. It might be a good idea to break this one out into a separate issue? 

> May we have another issue for improving "Device" model?

If there are changes needed to `Device` struct, then yes, please open a separate issue.

**Comment by tsconn23** [comment] 2019-01-30 23:11
I read through the current comments on this thread and it still has the flavor of discussion rather than requirements. My takeaway at this point is that we're already handling the point about DeviceObject vs DeviceResource naming in PR #1029. We can also file an issue, based on the above, to remove the `size`, `word` and `lsb` fields. The rest seems still up in the air and should perhaps be taken to a mailing list with the eventual result of a requirements doc from which more actionable issues can be created.

**Comment by tonyespy** [comment] 2019-02-05 14:12
> I just want to add my vote to those changes:
> 
>     * Remove `word`, `lsb`, and `signed` fields

Just reviewed your PR for this. Code looks good, just requested some more context in the commit message.

>     * Remove commands section

Why? I think we first need to properly document the differences between resources and commands, and how they work, before we decide to remove this section altogether.  Please see my earlier comment which included an email thread with @trcox about the command section.

I also mentioned that I have some concern as to whether or not the Core Metadata commands table is even being populated?
> 
>     * Remove `property` field in resource operation

Right, as it's always hard-coded to "property=value" in ever device profile resource.

+1

> 
>     * Remove `readWrite` and `defaultValue` in units

+1 on `readWrite`, but would like to review `defaultValue` first.

**Comment by tonyespy** [comment] 2019-02-05 14:18
> I read through the current comments on this thread and it still has the flavor of discussion rather than requirements. My takeaway at this point is that we're already handling the point about DeviceObject vs DeviceResource naming in PR #1029. We can also file an issue, based on the above, to remove the `size`, `word` and `lsb` fields. The rest seems still up in the air and should perhaps be taken to a mailing list with the eventual result of a requirements doc from which more actionable issues can be created.

Agreed. We discussed this at yesterday's device services WG meeting and @SteveOss and I agreed to work together to review the remaining proposed changes and present them one by one at next week's meeting. I'd also asked that we start creating & posting written meeting notes of the DS WG meetings so we can record/publicize decisions as we make them.

**Comment by iain-anderson** [comment] 2019-02-06 11:11
"size" attribute and binary blobs - I think we will need to support binary data where the size is variable. If we do that we won't need the attribute in the profile.

The only thing I can see that you could do in the commands section is to map a path that isn't
`/api/v1/device/{id}/{resource name}`
but we don't implement this and I don't think we should.

**Comment by jduranf** [comment] 2019-02-06 12:01
Currently commands are used for those things:
1. In device-sdk-go only it's used to check [if the Command exists](https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/handler/command.go#L56), with the same name as the related ResourceOperation
2. In core-command the [command ID it's used to populate the device commands](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/command/restDevice.go#L98)
3. In core-command the [command path it's used to communicate with the device](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/command/device.go#L34)
4. In core-data is [used to retrieve the associated device value descriptors](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/valuedescriptor.go#L131)

In my opinion, those things can/should be fixed/changed like this:
1. Just remove this check
2. core-command can use the Resources instead of the Commands to populate the device commands
3. In device-sdk-go the endpoints are populated using the Resources names, so core-command can use the Resources name to communicate with the device. This will solve a potential source of errors.
4. In device-sdk-go, valued descriptors are created using the DeviceResources, so use the DeviceResource in order to know the associated device value descriptors. This will solve another potential source of errors.

**Comment by jduranf** [comment] 2019-02-20 11:59
I just want to refresh the current status of this issue:
- Remove `readWrite` and `defaultValue` in units → Waiting @tonyespy about `defaultValue`
- Remove commands. After review the code and @tonyespy comments, I still think this can be a big simplification of the DeviceProfile
- `ResourceOperation` have `Object` and `Resource` fields. `Object` is used to point the `DeviceResource`, while `Resource` isn't used. I think this is confusing. I suggest to remove `Object` or `Resource` (or clarify how will be used `Resource`)

**Comment by tsconn23** [comment] 2019-07-22 18:59
Closing due to inactivity. It looks like we pulled some bits and pieces out of here and made changes. If there are any remaining discrete changes that people feel strongly about, create new issue. But since it's been five months with no activity on this, not going to leave it open any more.

**Closed by tsconn23** 2019-07-22 18:59 UTC
Labels: core-services, device-services, edinburgh, enhancement
