### ISSUE TITLE
Core data (in go) call of metadata to check device name/id not working 

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#71] opened 2018-03-21 23:36 UTC
Core data should allow a check of the existence of the device in any event to be checked in metadata.  Does not appear to be working.  This should also be a configurable option to turn or off the check based on level of trust the user has with data reported by device services (check at first and turn off later when the device is known to work well).

**Comment by tsconn23** [comment] 2018-05-08 01:31
I'm going to close this one as a duplicate of #128

**Closed by tsconn23** 2018-05-08 01:31 UTC
Labels: bug, core-services
