### ISSUE TITLE
HTTP request timeout when posting device with an unavailable device service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4238] opened 2022-11-29 05:19 UTC
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Levski

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/f644c248893353f17cef4898f552cf49b634b19c/docker-compose-no-secty.yml)
2. Stop device-virtual service
3. Create device with the following request body
```
[
   {
      "device":{
         "origin":1471806386919,
         "name":"Test-Device",
         "description":"Test-Device1",
         "adminState":"UNLOCKED",
         "operatingState":"UP",
         "protocols":{
            "other":{
               "Address":"simple01",
               "Port":"300"
            }
         },
         "labels":[
            "device-sample"
         ],
         "location":"{lat:45.45,long:47.80}",
         "serviceName":"device-virtual",
         "profileName":"Random-UnsignedInteger-Device"
      },
      "apiVersion":"v2"
   }
]
```
## 🔥 Exception or Error
<pre><code>

Got status code 503 with response 'HTTP request timeout'
Found error in core-metadata logs
level=ERROR ts=2022-11-29T05:15:16.22442393Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by FelixTing** [comment] 2022-12-02 09:40
This error appears from v2.3.1-dev.4 onwards.
I could not figure out the root cause but noticed it was related to the following code changes in v2.3.1-dev.4:
https://github.com/edgexfoundry/edgex-go/commit/a2765a98d8f71eb240f317e00f16757db580c473#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L16-R15
Before v2.3.1-dev.4, we set CGO_ENABLED=0 to build core-metadata service.
With the code changes in v2.3.1-dev.4, the value of CGO_ENABLED defaults to 1.

- The logs of the core-metadata service (built with `CGO_ENABLED=0`) while processing a POST request to add a new device:
```
level=WARN ts=2022-12-02T06:21:18.081413022Z app=core-metadata source=notify.go:80 msg="Skipping device validation for device Test-Device1 (device service device-virtual unavailable)"
level=DEBUG ts=2022-12-02T06:21:18.082964913Z app=core-metadata source=device.go:45 msg="Device created on DB successfully. Device ID: e74a6201-f322-49fa-a85e-225513e5eff9, Correlation-ID: 756d7796-7c11-4b4c-a554-404ac4966bba "
level=DEBUG ts=2022-12-02T06:21:18.083785918Z app=core-metadata source=device.go:264 msg="Published the 'add' Device System Event for device 'Test-Device1' to topic 'edgex/system-events/core-metadata/device/add/device-virtual/Random-UnsignedInteger-Device'"
level=ERROR ts=2022-12-02T06:21:18.084991923Z app=core-metadata source=notify.go:53 msg="fail to invoke device service callback for adding device Test-Device1, err: failed to send a http request -> Post \"http://edgex-device-virtual:59900/api/v2/callback/device\": dial tcp: lookup edgex-device-virtual on 127.0.0.11:53: server misbehaving"
```

- The logs of the core-metadata service (built with `CGO_ENABLED=1`) while processing a POST request to add a new device:
```
level=WARN ts=2022-12-02T06:25:22.337687381Z app=core-metadata source=notify.go:80 msg="Skipping device validation for device Test-Device (device service device-virtual unavailable)"
level=DEBUG ts=2022-12-02T06:25:22.339081123Z app=core-metadata source=device.go:45 msg="Device created on DB successfully. Device ID: 2c4d5361-93cd-46f0-8dab-e5fddea0ca31, Correlation-ID: 41af2392-77ed-4340-9a88-3424aa9db94a "

level=ERROR ts=2022-12-02T06:25:22.339307945Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"

level=DEBUG ts=2022-12-02T06:25:22.339704311Z app=core-metadata source=device.go:264 msg="Published the 'add' Device System Event for device 'Test-Device' to topic 'edgex/system-events/core-metadata/device/add/device-virtual/Random-UnsignedInteger-Device'"
(after 5 seconds...)
level=ERROR ts=2022-12-02T06:25:27.349901204Z app=core-metadata source=notify.go:53 msg="fail to invoke device service callback for adding device Test-Device, err: failed to send a http request -> Post \"http://edgex-device-virtual:59900/api/v2/callback/device\": dial tcp: lookup edgex-device-virtual: Try again"
```

As we plan to replace device validation callback with message bus request/response (#4236), it does not seem worthwhile to continue digging into this issue.

**Comment by cloudxxx8** [comment] 2022-12-02 09:44
Close this issue because we decided to not allow Device creation and update without Device Service in the Core WG meeting on Nov 27.  The Device validation process is necessary for the future release.

**Closed by cloudxxx8** 2022-12-02 09:44 UTC
Labels: bug
